In [29]:
import pandas as pd

In [91]:
import numpy as np

In [65]:
from sklearn.linear_model import LogisticRegression

In [30]:
df=pd.read_csv(r'C:\Users\Bala murukan\zaga-nec-hackathon-2\loanprediction.csv')

In [31]:
df.head()

,BAD,LOAN,MORTDUE,VALUE,REASON,JOB,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC
0,1,1100,25860.0,39025.0,HomeImp,Other,10.5,0.0,0.0,94.366667,1.0,9.0,NaN
1,1,1300,70053.0,68400.0,HomeImp,Other,7.0,0.0,2.0,121.833333,0.0,14.0,NaN
2,1,1500,13500.0,16700.0,HomeImp,Other,4.0,0.0,0.0,149.466667,1.0,10.0,NaN
3,1,1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,1700,97800.0,112000.0,HomeImp,Office,3.0,0.0,0.0,93.333333,0.0,14.0,NaN

In [32]:
df.tail()

,BAD,LOAN,MORTDUE,VALUE,REASON,JOB,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC
5955,0,88900,57264.0,90185.0,DebtCon,Other,16.0,0.0,0.0,221.808718,0.0,16.0,36.112347
5956,0,89000,54576.0,92937.0,DebtCon,Other,16.0,0.0,0.0,208.692070,0.0,15.0,35.859971
5957,0,89200,54045.0,92924.0,DebtCon,Other,15.0,0.0,0.0,212.279697,0.0,15.0,35.556590
5958,0,89800,50370.0,91861.0,DebtCon,Other,14.0,0.0,0.0,213.892709,0.0,16.0,34.340882
5959,0,89900,48811.0,88934.0,DebtCon,Other,15.0,0.0,0.0,219.601002,0.0,16.0,34.571519

In [33]:
df.shape

(5960, 13)

In [34]:
df.columns

Index(['BAD', 'LOAN', 'MORTDUE', 'VALUE', 'REASON', 'JOB', 'YOJ', 'DEROG',
       'DELINQ', 'CLAGE', 'NINQ', 'CLNO', 'DEBTINC'],
      dtype='object')

In [35]:
df['REASON'].unique()

array(['HomeImp', nan, 'DebtCon'], dtype=object)

In [36]:
df['REASON']=df['REASON'].map({'HomeImp':0,'DebtCon':1,'NaN':2})

In [37]:
df['REASON'].unique()

array([ 0., nan,  1.])

In [38]:
median = df['REASON'].median()
df['REASON']=df['REASON'].fillna(median)

In [39]:
df['REASON'].unique()

array([0., 1.])

In [40]:
df['JOB'].unique()

array(['Other', nan, 'Office', 'Sales', 'Mgr', 'ProfExe', 'Self'],
      dtype=object)

In [41]:
df['JOB']=df['JOB'].map({'Other':1,'Sales':2,'Mgr':3,'ProfExe':'4','Self':'5'})

In [42]:
df['JOB'].unique()

array([1, nan, 2, 3, '4', '5'], dtype=object)

In [43]:
median = df['JOB'].median()
df['JOB']=df['JOB'].fillna(median)

In [44]:
df['JOB'].unique()

array([1, 2, 3, '4', '5'], dtype=object)

In [45]:
df.columns

Index(['BAD', 'LOAN', 'MORTDUE', 'VALUE', 'REASON', 'JOB', 'YOJ', 'DEROG',
       'DELINQ', 'CLAGE', 'NINQ', 'CLNO', 'DEBTINC'],
      dtype='object')

In [46]:
df.head()

,BAD,LOAN,MORTDUE,VALUE,REASON,JOB,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC
0,1,1100,25860.0,39025.0,0.0,1,10.5,0.0,0.0,94.366667,1.0,9.0,NaN
1,1,1300,70053.0,68400.0,0.0,1,7.0,0.0,2.0,121.833333,0.0,14.0,NaN
2,1,1500,13500.0,16700.0,0.0,1,4.0,0.0,0.0,149.466667,1.0,10.0,NaN
3,1,1500,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,1700,97800.0,112000.0,0.0,1.0,3.0,0.0,0.0,93.333333,0.0,14.0,NaN

In [47]:
df.tail()

,BAD,LOAN,MORTDUE,VALUE,REASON,JOB,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC
5955,0,88900,57264.0,90185.0,1.0,1,16.0,0.0,0.0,221.808718,0.0,16.0,36.112347
5956,0,89000,54576.0,92937.0,1.0,1,16.0,0.0,0.0,208.692070,0.0,15.0,35.859971
5957,0,89200,54045.0,92924.0,1.0,1,15.0,0.0,0.0,212.279697,0.0,15.0,35.556590
5958,0,89800,50370.0,91861.0,1.0,1,14.0,0.0,0.0,213.892709,0.0,16.0,34.340882
5959,0,89900,48811.0,88934.0,1.0,1,15.0,0.0,0.0,219.601002,0.0,16.0,34.571519

In [48]:
df['CLAGE'].unique()

array([ 94.36666667, 121.83333333, 149.46666667, ..., 212.27969667,
       213.89270901, 219.60100218], shape=(5315,))

In [49]:
df.drop_duplicates()

,BAD,LOAN,MORTDUE,VALUE,REASON,JOB,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC
0,1,1100,25860.0,39025.0,0.0,1,10.5,0.0,0.0,94.366667,1.0,9.0,NaN
1,1,1300,70053.0,68400.0,0.0,1,7.0,0.0,2.0,121.833333,0.0,14.0,NaN
2,1,1500,13500.0,16700.0,0.0,1,4.0,0.0,0.0,149.466667,1.0,10.0,NaN
3,1,1500,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,1700,97800.0,112000.0,0.0,1.0,3.0,0.0,0.0,93.333333,0.0,14.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5955,0,88900,57264.0,90185.0,1.0,1,16.0,0.0,0.0,221.808718,0.0,16.0,36.112347
5956,0,89000,54576.0,92937.0,1.0,1,16.0,0.0,0.0,208.692070,0.0,15.0,35.859971
5957,0,89200,54045.0,92924.0,1.0,1,15.0,0.0,0.0,212.279697,0.0,15.0,35.556590
5958,0,89800,50370.0,91861.0,1.0,1,14.0,0.0,0.0,213.892709,0.0,16.0,34.340882
5959,0,89900,48811.0,88934.0,1.0,1,15.0,0.0,0.0,219.601002,0.0,16.0,34.571519

In [50]:
df.shape

(5960, 13)

In [53]:
median = df['CLAGE'].median()
df['CLAGE']=df['CLAGE'].fillna(median)

In [54]:
df.head()

,BAD,LOAN,MORTDUE,VALUE,REASON,JOB,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC
0,1,1100,25860.0,39025.0,0.0,1,10.5,0.0,0.0,94.366667,1.0,9.0,NaN
1,1,1300,70053.0,68400.0,0.0,1,7.0,0.0,2.0,121.833333,0.0,14.0,NaN
2,1,1500,13500.0,16700.0,0.0,1,4.0,0.0,0.0,149.466667,1.0,10.0,NaN
3,1,1500,NaN,NaN,1.0,1.0,NaN,NaN,NaN,173.466667,NaN,NaN,NaN
4,0,1700,97800.0,112000.0,0.0,1.0,3.0,0.0,0.0,93.333333,0.0,14.0,NaN

In [55]:
median = df['CLNO'].median()
df['CLNO']=df['CLNO'].fillna(median)

In [56]:
median = df['DEBTINC'].median()
df['DEBTINC']=df['DEBTINC'].fillna(median)

In [57]:
median = df['NINQ'].median()
df['NINQ']=df['NINQ'].fillna(median)

In [58]:
median = df['DELINQ'].median()
df['DELINQ']=df['DELINQ'].fillna(median)

In [59]:
median = df['VALUE'].median()
df['VALUE']=df['VALUE'].fillna(median)

In [61]:
median = df['VALUE'].median()
df['VALUE']=df['VALUE'].fillna(median)

In [60]:
median = df['MORTDUE'].median()
df['MORTDUE']=df['MORTDUE'].fillna(median)

In [62]:
median = df['YOJ'].median()
df['YOJ']=df['YOJ'].fillna(median)

In [63]:
df.head()

,BAD,LOAN,MORTDUE,VALUE,REASON,JOB,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC
0,1,1100,25860.0,39025.0,0.0,1,10.5,0.0,0.0,94.366667,1.0,9.0,34.818262
1,1,1300,70053.0,68400.0,0.0,1,7.0,0.0,2.0,121.833333,0.0,14.0,34.818262
2,1,1500,13500.0,16700.0,0.0,1,4.0,0.0,0.0,149.466667,1.0,10.0,34.818262
3,1,1500,65019.0,89235.5,1.0,1.0,7.0,NaN,0.0,173.466667,1.0,20.0,34.818262
4,0,1700,97800.0,112000.0,0.0,1.0,3.0,0.0,0.0,93.333333,0.0,14.0,34.818262

In [64]:
median = df['DEROG'].median()
df['DEROG']=df['DEROG'].fillna(median)

In [100]:
df.head()

,BAD,LOAN,MORTDUE,VALUE,REASON,JOB,YOJ,DEROG,DELINQ,CLAGE,NINQ,CLNO,DEBTINC
0,1,1100,25860.0,39025.0,0.0,1,10.5,0.0,0.0,94.366667,1.0,9.0,34.818262
1,1,1300,70053.0,68400.0,0.0,1,7.0,0.0,2.0,121.833333,0.0,14.0,34.818262
2,1,1500,13500.0,16700.0,0.0,1,4.0,0.0,0.0,149.466667,1.0,10.0,34.818262
3,1,1500,65019.0,89235.5,1.0,1.0,7.0,0.0,0.0,173.466667,1.0,20.0,34.818262
4,0,1700,97800.0,112000.0,0.0,1.0,3.0,0.0,0.0,93.333333,0.0,14.0,34.818262

In [98]:
X=df[['LOAN','VALUE']]
y=df['REASON']
model=LogisticRegression()

In [99]:
model.fit(X,y)
print(model.predict(X))

[1. 1. 1. ... 1. 1. 1.]